# Generated by Django 5.2.3 on 2025-07-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_doc', models.CharField(max_length=15)),
                ('documento_identidad', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('distrito', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('enlace_acceso', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=100)),
                ('es_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibroReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_slug', models.SlugField(blank=True)),
                ('establecimiento_slug', models.SlugField()),
                ('codigo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='reclamaciones.establecimiento')),
            ],
            options={
                'unique_together': {('libro_slug', 'establecimiento_slug')},
            },
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='reclamaciones.marca'),
        ),
        migrations.AddField(
            model_name='marca',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='reclamaciones.proveedor'),
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('codigo_hoja', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo')], max_length=20)),
                ('tipo_bien', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], max_length=20)),
                ('descripcion_bien', models.TextField()),
                ('monto_reclamado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalle', models.TextField()),
                ('solicitud_cliente', models.TextField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones', to='reclamaciones.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='reclamaciones.estadoreclamacion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones', to='reclamaciones.libroreclamacion')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=255)),
                ('reclamacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='reclamaciones.reclamacion')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_doc', models.CharField(max_length=15)),
                ('documento_identidad', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='reclamaciones.cliente')),
            ],
        ),
    ]
