# Generated by Django 5.2.3 on 2025-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='documento_identidad',
            new_name='doc_id_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo_doc',
            new_name='tipo_doc_cliente',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='direccion',
            new_name='direccion_establecimeinto',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='nombre',
            new_name='nombre_establecimiento',
        ),
        migrations.RenameField(
            model_name='estadoreclamacion',
            old_name='nombre',
            new_name='nombre_estado_reclamo',
        ),
        migrations.RenameField(
            model_name='libroreclamacion',
            old_name='codigo',
            new_name='codigo_libro',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='nombre',
            new_name='nombre_marca',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='direccion',
            new_name='domicilio_fiscal',
        ),
        migrations.RenameField(
            model_name='representantelegal',
            old_name='documento_identidad',
            new_name='doc_id_representante',
        ),
        migrations.RenameField(
            model_name='representantelegal',
            old_name='nombre',
            new_name='nombre_representante',
        ),
        migrations.RenameField(
            model_name='representantelegal',
            old_name='tipo_doc',
            new_name='tipo_doc_representante',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
