# Generated by Django 5.2.3 on 2025-08-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0002_rename_documento_identidad_cliente_doc_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimiento',
            old_name='direccion_establecimeinto',
            new_name='direccion_establecimiento',
        ),
    ]
